[package]
name = "coresuite-editor"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CoreSuite Editor"
publish = false

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
coresuite-shell = { workspace = true }
tauri = { workspace = true }
